name: Build

on:
    push:
        branches:
            - master
        paths-ignore:
            - '*.md'
            - 'docs/**'
            - 'load-tests/**'

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.repository_owner == 'ballerina-platform'
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Generate CodeCov Report
                uses: codecov/codecov-action@v3
                with:
                    files: ballerina/target/report/graphql/coverage-report.xml
